### ISSUE TITLE
After updating stale rust-stable sha256, Rust backend doesn't build

### ISSUE THREAD

**Issue by leungbk** [nix-community/todomvc-nix#20]
On [this branch](https://github.com/leungbk/todomvc-nix/tree/update-rust), I updated the `rust-stable` sha256 since it was old. After doing that, I couldn't build the Rust backend, so I tried `cargo update`, but still couldn't build. I ran `nix flake update` hoping that would improve the situation, but no dice. After doing all of this, here's what happens when I try to build the backend:

```
   Compiling tide v0.13.0
   Compiling sqlx-macros v0.3.5
error[E0277]: the trait bound `std::string::String: log::kv::value::ToValue` is not satisfied
  --> /build/rust-backend-0.1.0-vendor.tar.gz/tide/src/log/middleware.rs:43:9
   |
43 | /         log::info!("<-- Request received", {
44 | |             method: method,
45 | |             path: path,
46 | |         });
   | |___________^ the trait `log::kv::value::ToValue` is not implemented for `std::string::String`
   |
   = note: required for the cast to the object type `dyn log::kv::value::ToValue`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

I'm not knowledgeable with Rust, so I'm not sure how to handle this.

**Comment by Rizary** [comment]
@leungbk I have create PR for updating rust stable version. I can't reproduce your error so I update it myself.
